ALTER TABLE orders ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'Normal';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS prod_start DATE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS prod_end DATE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivered_date DATE;

ALTER TABLE pricing_settings ADD COLUMN IF NOT EXISTS work_days NUMERIC DEFAULT 5;
ALTER TABLE pricing_settings ADD COLUMN IF NOT EXISTS work_hours NUMERIC DEFAULT 8;
ALTER TABLE pricing_settings ADD COLUMN IF NOT EXISTS cap_buffer NUMERIC DEFAULT 10;
